name: gdpr-obfuscator

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    # if: false # this will cause the job to be skipped - delete to enable
    name: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create-Environment
        run: make create-environment
      - name: Install Modules
        run: make dev-setup

      - name: safety check
        uses: pyupio/safety-action@v1

      - name: run-all-checks
        run: make run-checks